name: "Upload Python Package"

on:
  release:
    types: [published]
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    uses: ego-lay-atman-bay/python-publish-workflow/.github/workflows/python-publish.yml@main
    with:
        python_version: '3.14'
