name: Sphinx build

on: 
  release:
    types: [created]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run:
        sudo apt-get install python3-tk -y &&
        pip install -r doc-build/requirements.txt
    
    - name: Upload artifacts
      run:
        sphinx-build -b html doc-build docs
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: docs/
