name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run:
        pip install -U sphinx &&
        pip install -r requirements.txt
    
    - name: Upload artifacts
      run:
        sphinx-build -b html doc-build docs
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: docs/
